NAME = libft.a

CC = gcc
CCFLAGS = -Wall -Werror -Wextra
SRCS = ft_atoi.c ft_isalnum.c ft_isalpha.c ft_isascii.c ft_isdigit.c ft_isprint.c\
	   ft_strchr.c ft_strlen.c ft_strrchr.c ft_strncmp.c ft_strnstr.c ft_tolower.c ft_toupper.c\

OBJS = $()


.PHONY : clean
clean : -rm $(OBJS)